### PR TITLE
Fix type of AccountSource.fields

### PR DESCRIPTION
**Pull request by johnspurlock-skymethod**

### CODE REVIEW

**Comment by neet** [comment]
@johnspurlock-skymethod  Thank you for the PR
I will take some time to merge this since CI is broken in the main branch 🙏

**Comment by johnspurlock-skymethod** [comment]
thanks - and thank you for this project

**Comment by neet** [comment]
@johnspurlock-skymethod I'm sorry for taking a long to merge your pull request. It has been merged now and released as a `v6.8.1` #1169 🙏

**Comment by neet** [comment]
I've already been working on it! #1155

**Pull request merged**
